ci: build package, upload codegen and packages

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,44 +1,55 @@
-name: CI
+name: build
 on:
-  create: # when tags are created
-  push:
-    branches: [ master ]
-  pull_request:
-    branches: [ master ]
+  workflow_dispatch:
+
+env:
+  PROJECT_SOURCE_DIR: ./src
+  PROJECT_CONFIGURATION: Release
+  PROJECT_ARTIFACTS_DIR: ./bin/Release/
+
 jobs:
-  Build_Windows:
+  build:
     runs-on: windows-latest
     steps:
-    - name: Checkout Repository
+    - name: Checkout
       uses: actions/checkout@v3
       with:
         fetch-depth: 0
 
-    - name: Install .NET
+    - name: Setup .NET
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: 7.0.x
 
-    - name: Restore dependencies
+    - name: Restore
       run: dotnet restore src
 
-    - name: Build Project
+    - name: Build
       run: dotnet build -c Release --no-restore src
 
-    - name: Build Packages
+    - name: Pack
       run: dotnet pack src/ImGui.NET -c Release --no-restore --no-build
 
-    - name: List Packages
-      run: ls -l bin\Release\ImGui.NET\
+    - name: Upload code generator
+      uses: actions/upload-artifact@v3
+      with:
+        name: CodeGenerator
+        path: ${{ env.PROJECT_ARTIFACTS_DIR }}/CodeGenerator/net7.0/
 
-    - name: Validate Generated Code
-      if: startsWith(github.ref, 'refs/tags/')
-      shell: bash
-      run: |
-        echo "Running CodeGenerator"
-        bin/Release/CodeGenerator/net7.0/CodeGenerator.exe "src/ImGui.NET/Generated"
-        git status -s | findstr . && echo "ERROR: CodeGenerator is not executed, please execute it." && exit 1 || exit 0
+    - name: Upload packages
+      uses: actions/upload-artifact@v3
+      with:
+        name: NuGet packages
+        path: ${{ env.PROJECT_ARTIFACTS_DIR }}/ImGui.NET/*.nupkg
 
-    - name: Publish to nuget.org
-      if: startsWith(github.ref, 'refs/tags/')
-      run: dotnet nuget push bin\Release\ImGui.NET\*.nupkg -s https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_KEY}}
+    # - name: Validate Generated Code
+    #   if: startsWith(github.ref, 'refs/tags/')
+    #   shell: bash
+    #   run: |
+    #     echo "Running CodeGenerator"
+    #     bin/Release/CodeGenerator/net7.0/CodeGenerator.exe "src/ImGui.NET/Generated"
+    #     git status -s | findstr . && echo "ERROR: CodeGenerator is not executed, please execute it." && exit 1 || exit 0
+
+    # - name: Publish to nuget.org
+    #   if: startsWith(github.ref, 'refs/tags/')
+    #   run: dotnet nuget push bin\Release\ImGui.NET\*.nupkg -s https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_KEY}}
